version: "3.9" # o '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gymmanager_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSuperSeguro123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: gymmanager_api
    restart: always
    ports:
      - "7093:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GymManagerDbContext=Server=db;Database=GymManagerDb;User Id=sa;Password=TuPasswordSuperSeguro123!;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.client
    container_name: gymmanager_blazor
    restart: always
    ports:
      - "7083:80"
    depends_on:
      - api

  seq:
    image: datalust/seq:latest
    container_name: gymmanager_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data

volumes:
  sqlvolume:
  seq-data:
