# Etapa de compilación
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "GymManager.Client/GymManager.Client.csproj" -c Release -o /app/publish

# Etapa de servidor (Nginx)
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Copiamos los archivos estáticos de Blazor a la carpeta de Nginx
COPY --from=build /app/publish/wwwroot .

# Copiamos una configuración básica de Nginx para Blazor (opcional, pero recomendada)
EXPOSE 80
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]