FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY GymManager.Api/GymManager.Api.csproj GymManager.Api/
COPY GymManager.Shared/GymManager.Shared.csproj GymManager.Shared/

RUN dotnet restore GymManager.Api/GymManager.Api.csproj

COPY . .

RUN dotnet publish GymManager.Api/GymManager.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "GymManager.Api.dll"]